### PR TITLE
Controller: add logging to push/pull

### PR DESCRIPTION
**Pull request by sergiogiro**
It's a poor man's progress bar while we have something better

### CODE REVIEW

**Comment by SamirTalwar** [comment]
I don't understand why the logging level of the controller should be responsible for deciding whether the output stream is sent to the client or not. Just send it and let the client decide.

Perhaps the client-side `quiet_build` configuration option could be renamed `quiet` and used to decide whether the push/pull logs are shown or not.

**Comment by sergiogiro** [comment]
It's not sending to the client in any case. It's logging or not. There's no
point in setting stream=True (possibly increasing data transfer, etc) if
you're not going to look at the stream at all, hence the condition.

**Comment by SamirTalwar** [comment]
Sorry, misread the PR. But why not send it to the client? I don't want someone to be pinging me asking why their transfer isn't working if they can see for themselves. 😉

**Comment by sergiogiro** [comment]
Because that's an extra feature for users, we can do that in another PR ;)

**Comment by SamirTalwar** [comment]
OK, but this one as it is has problems. Primarily that this moves away from ops-governed logging and towards application logic baked into the logging layer.

[The Twelve-Factor App has more to say on logs](https://12factor.net/logs).

Basically, just log everything. It's not for the application to know when logs will be useful, it's for the person debugging the application. So making a decision up-front about which logs to show makes the logs useless. Best to just spit everything out and then decide what to filter out later.

[As always, Charity Majors nails it.](https://honeycomb.io/blog/2017/04/lies-my-parents-told-me-about-logs/)

**Comment by sergiogiro** [comment]
> OK, but this one as it is has problems. Primarily that this moves away
from ops-governed logging and towards application logic baked into the
logging layer.

Just to understand what you're trying to say. You'd be ok if we'd always
set stream=True and we loop though the messages anyway, even if nothing
gets logged in the end?

(Also, it's still ops-governed, it will log or not according to the debug
level coming from the outside.)

**Comment by SamirTalwar** [comment]
Yes, the idea is that you just set the logging level to `debug` and then filter later.

**Pull request merged**
