### PR TITLE
Controller: specify docker runtime

### PR DESCRIPTION
**Pull request by sergiogiro**
We need it for nvidia things

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Why not just always use the NVIDIA runtime?

**Comment by sergiogiro** [comment]
Because we want the tool to be fairly general? Might be it was useful to
just hardcode it for now, but now it's done (and didn't take much effort).

**Comment by SamirTalwar** [comment]
Well, it's one more thing the user has to specify. Why bother?

**Comment by sergiogiro** [comment]
We can make nvidia the default. Will it work regardless of the docker image?

**Comment by SamirTalwar** [comment]
Also, it's not like we can use any runtime except the default and "nvidia".

**Comment by SamirTalwar** [comment]
Yes, it will work for all Docker images AFAIK.

**Comment by SamirTalwar** [comment]
Ah, build's failing. OK, now I see a use case for making it configurable. 😉 

Feel free to revert the previous commit and merge.

**Comment by sergiogiro** [comment]
Ha, I thought you were joking, but it really fails.

**Pull request merged**
